version: '3'

services:
  nginx:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
    #volumes:
     # - /var/run/docker.sock:/tmp/docker.sock:ro

  next-app:
    container_name: frontend
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 8080:3000
    networks:
      - my_network
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=front.local
      - VIRTUAL_PORT=8000

  node-app:
    container_name: backend
    build:
      context: ./node-app
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
    restart: always
    
    ports:
      - 3000:3000
    networks:
      - my_network
    

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
